name: Telegram Digest

on:
  schedule:
    # daily 08:00 MSK (05:00 UTC)
    - cron:  '0 5 * * *'
    # weekly — Пн 08:15 MSK
    - cron:  '15 5 * * 1'
    # monthly — 1‑е число 08:30 MSK
    - cron:  '30 5 1 * *'
  workflow_dispatch:      # ручной запуск из UI

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TG_TOKEN:       ${{ secrets.TG_TOKEN }}
      CHAT_ID:        ${{ secrets.CHAT_ID }}
    strategy:
      matrix:
        period: [daily, weekly, monthly]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: |
          PERIOD=${{ matrix.period }} python digest_to_tg.py
