name: Telegram Digest   # заголовок в Actions

on:
  workflow_dispatch:    # только ручной запуск

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TG_TOKEN:       ${{ secrets.TG_TOKEN }}
      CHAT_ID:        ${{ secrets.CHAT_ID }}
      NEWS_API_KEY:   ${{ secrets.NEWS_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - run: python digest_to_tg.py
